//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaDeFacturacion.fonts.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetallesCotizacion
    {
        public int idDetalle { get; set; }
        public int idCotizacion { get; set; }
        public string idProducto { get; set; }
        public decimal cantidad { get; set; }
        public decimal precio { get; set; }
        public Nullable<decimal> descuento { get; set; }
        public Nullable<decimal> subTotal { get; set; }
    
        public virtual Cotizaciones Cotizaciones { get; set; }
        public virtual Productos Productos { get; set; }
    }
}
